config/routes.rb
StaticPagesApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  get "users/new"

  get "static_pages/home"
=begin
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
=end
  resources :sessions, only: [:new, :create, :destroy]
  get "users/new"

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get "users/new"










  root :to => 'static_pages#home'


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'Conocenos') %>
  <h1>Conocenos</h1>
  <p>
  Somos unos estudaintes haciendo un tutorial de <a href="http://ruby.railstutorial.org">Ruby on Rails</a>
  </p>
  <ul id="lista_nombres">
    <li>Omar BenitezEscajeda</li>
    <li>Ingrid Pinedo Pantoja</li>
    <li>Macario De la Peña Valencia</li>
  </ul>

app/views/static_pages/contact.html.erb
<% provide(:title,'Contacto') %>
<h1>Contacto</h1>
<p>Contactanos en<a href='static-page-app.herokuapp.com'> esta pagina</a>.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Ayuda') %>
<h1>Ayuda</h1>
<p>
  Para más ayuda, visita el tutorial de Ruby on Rails en:
  <a href="http://railstutorial.org/help">Ruby on Rails</a>.
  Para conseguir ayuda en esta aplicación de muestra, visita: 
  <a href="http://railstutorial.org/book">Tutorial de Rails</a>.
</p>

app/views/static_pages/home.html.erb


  <% if signed_in? %>
      <div class="row">
        <aside class="span4">
          <section>
            <%= render 'shared/user_info' %>
          </section>
          <section>
            <%= render 'shared/stats' %>
          </section>
          <section>
            <%= render 'shared/micropost_form' %>
          </section>
        </aside>
        <div class="span8">
          <h3>Publicaciones</h3>
          <%= render 'shared/feed' %>
        </div>
      </div>
  <% else %>
      <div class="center hero-unit">
  <h1>Bienvenidos</h1>

  <h2>
    Esta es la pagina de inicio de la aplicacion <%= link_to 'Equipo BOB', about_path %>
  </h2>

  <%= link_to "Registrate!", signup_path , class: "btn btn-large btn-primary" %>
      </div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

<% end %>