config/routes.rb
StaticPagesApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  get "users/new"

  get "static_pages/home"
=begin
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
=end
  resources :sessions, only: [:new, :create, :destroy]
  get "users/new"

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get "users/new"










  root :to => 'static_pages#home'


end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by team BOB
  </small>
  <nav>
    <ul>
      <li><%= link_to "Conocenos", about_path %></li>
      <li><%= link_to "Contacto", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Tutorial de Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BOB Team", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Inicio", root_path %></li>
          <li><%= link_to "Ayuda",   help_path %></li>
          <% if signed_in? %>
              <li><%= link_to "Usuarios", "/users" %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Cuenta <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Perfil", current_user %></li>
                  <li><%= link_to "Configuracion", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to 'Salir', signout_url, :method => "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Ingresa", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= fulltitle(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>